### ISSUE TITLE
Request: Footnotes for different panel states

### ISSUE THREAD

**Issue by me0wday** [glucasroe/Panel-Exploder#1]
Would it be possible to include the footnotes for the different panel states when exploded in the modal?

**Comment by glucasroe** [comment]
**Short answer**: Maybe, but I don't know how.

**Longer answer**: I've been trying to get notes working, but I can't seem to get any sort of response back no matter how deep I delve into the compiled code and attempt to reverse engineer it. Here's what I do remember:
- Notes are stored in a data file at `files > pageName > data.js` where it is mapped to a minified data object.
- The data is returned as a minified function of `_creator`
- I haven't been able to accurately return any values from the notes data by pulling snippets of axure's generator code yet

What I _can_ tell you is that if I can somehow figure out how to get notes to work, then they could easily be used to add footnotes. Outside of the notes though, I don't see a way to add arbitrary text markup to a panel without adding in strange extraneous things.

**Comment by me0wday** [comment]
Would it be possible to extend/rewrite the inbuilt axure function that adds notes (ie. when you add an interaction to change the state of a dynamic panel it must be called again). 

Or simply call the function again once the exploded view has been displayed? Ie. to use their own method to re-apply the footnotes on top of the exploded panel?

**Comment by me0wday** [comment]
Bump 👯‍♂️

**Comment by glucasroe** [comment]
When I read this a few months ago, I thought you just hadn't read my response which is why I didn't respond. I now realize that I misread what you said.

In short, those are both things that I've tried but haven't been able to get working for some reason. I'm not currently working on this project though.

**Comment by me0wday** [comment]
Bugger okay, do you have plans to make any improvements to it? I believe it is very useful for visual specs.

**Comment by glucasroe** [comment]
At this point, I feel like I've done what I can for this project. I still return to it on occasion, and will let you know if I figure anything out!
